const mongoose =require('mongoose');
const{Schema}=mongoose;
const userSchema=new Schema({
    id:{
        type:Number,
        required:true
    },
    name:{
        type:String,
        required:true
    },
    email:{
        type:String,
        required:true,
        uniqe:true
    },
    phoneNo:{
        type:Number,
        required:true
    },
    address:{
        type:String,
        required:true
    },
    bookName:{
        type:String,
        required:true
    },
    dollar:{
        type:Number,
        required:true
    },
    image:{
        type:String,
        required:true
    },
    paymentMethod:{
        type:String,
        required:true
    },
    date:{
        type:Date,
        default:Date.now
    },
});
module.exports=mongoose.model('user',userSchema);
